const photo = (id: string, w = 900) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=${w}&q=85`;
export const initial = [
  {
    id: "1",
    title: "İlkbaharın fısıltısı",
    category: "Dijital sanat",
    year: "2025",
    date: "2025-04-12",
    medium: "Procreate · Dijital boyama",
    tags: ["Doğa", "Düşsel"],
    image: photo("photo-1493976040374-85c8e12f0c0e"),
    description:
      "Bazı yerler bir manzaradan çok, bir his gibidir. İlkbaharın usulca dokunduğu bir dünyada, zamanın biraz daha yavaş akmasını hayal ettim.",
    ratio: "tall",
  },
  {
    id: "2",
    title: "Sessizliğin kıyısında",
    category: "Fotoğraf",
    year: "2025",
    date: "2025-03-18",
    medium: "Dijital fotoğraf · Lightroom",
    tags: ["Doğa", "Minimal"],
    image: photo("photo-1470770841072-f978cf4d019e"),
    description:
      "Dağların göle bıraktığı bir hatıra. Günün henüz başlamadığı o kısa, sessiz aralık.",
    ratio: "short",
  },
  {
    id: "3",
    title: "Güneşin hatırası",
    category: "Dijital sanat",
    year: "2024",
    date: "2024-08-24",
    medium: "Photoshop · Dijital kolaj",
    tags: ["Soyut", "Sıcak tonlar"],
    image: photo("photo-1500534623283-312aade485b7"),
    description:
      "Yazın son ışığı, aklımda kalan sıcak renkler ve hiçbir yere yetişme telaşı olmayan bir gün.",
    ratio: "medium",
  },
  {
    id: "4",
    title: "Geceye doğru",
    category: "Fotoğraf",
    year: "2025",
    date: "2025-01-08",
    medium: "Dijital fotoğraf",
    tags: ["Şehir", "Gece"],
    image: photo("photo-1519608487953-e999c86e7455"),
    description:
      "Gece, bildiğimiz dünyayı yeniden çizer. Maviye karışan son ışıkların peşinde.",
    ratio: "tall",
  },
  {
    id: "5",
    title: "Yavaşça, yeniden",
    category: "İllüstrasyon",
    year: "2024",
    date: "2024-06-11",
    medium: "Suluboya · Kâğıt",
    tags: ["Doğa", "Minimal"],
    image: photo("photo-1441974231531-c6227db76b6e"),
    description: "Doğanın kendi ritmini dinlemek üzerine küçük bir çalışma.",
    ratio: "tall",
  },
  {
    id: "6",
    title: "Bulutların ötesi",
    category: "Dijital sanat",
    year: "2025",
    date: "2025-02-20",
    medium: "Procreate · Dijital boyama",
    tags: ["Düşsel", "Pastel"],
    image: photo("photo-1470252649378-9c29740c9fa8"),
    description:
      "Gerçekle düş arasındaki o ince çizgide, kendime bir yer aradım.",
    ratio: "medium",
  },
  {
    id: "7",
    title: "Bir yaz düşü",
    category: "Fotoğraf",
    year: "2024",
    date: "2024-07-17",
    medium: "Analog fotoğraf · 35mm",
    tags: ["Doğa", "Sıcak tonlar"],
    image: photo("photo-1464822759023-fed622ff2c3b"),
    description: "Uzaklara bakmak bazen eve dönmek gibidir.",
    ratio: "short",
  },
  {
    id: "8",
    title: "Suyun hafızası",
    category: "İllüstrasyon",
    year: "2024",
    date: "2024-05-04",
    medium: "Akrilik · Tuval",
    tags: ["Soyut", "Doğa"],
    image: photo("photo-1518837695005-2083093ee35b"),
    description:
      "Her dalga bir öncekini hatırlar mı? Mavinin katmanlarında bir arayış.",
    ratio: "medium",
  },
];
